### ISSUE TITLE
exception when using minified Nette

### ISSUE THREAD

**Issue by Ciki** [Kdyby/BootstrapFormRenderer#25]
https://github.com/Kdyby/BootstrapFormRenderer/blob/master/src/Kdyby/BootstrapFormRenderer/DI/RendererExtension.php#L25 causes exception if using minified version of Nette (there's no Nette loader present)

**Comment by fprochazka** [comment]
I'm not sure I consider this as a bug. I really don't see any benefits in minified Nette.

**Comment by Ciki** [comment]
I don't say there are some I just expected this addon to work with it. At least it could be mentioned somewhere..

**Comment by mishak87** [comment]
Well there is check for existence of compatibility classes why not add check for loader?

**Comment by fprochazka** [comment]
@ciki I'm always saying I support only composer, nothing else. I'm not actively trying to prevent anyone from using other installation methods, but I'm not actively supporting them. So there is that :)

@mishak87 Because without the loader the hack wouldn't work. On the other hand. I might as well drop the support for old dev nette.

**Comment by Ciki** [comment]
OK, from now on I know it :)
